from pkgutil import extend_path
from string import printable
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import os

repo_path = os.path.expanduser("Canada.xlsx")

df_Canada = pd.read_excel(os.path.join(repo_path), skiprows=range(20), skipfooter=29)

print("Data downloaded and read into a dataframe!")

years = list(map(str, range(1980, 2014)))

# drop unnecessary columns
df_Canada.drop(["AREA", "REG", "DEV", "Type", "Coverage"], axis=1, inplace=True)
# rename columns
df_Canada.rename(
    columns={"OdName": "Country", "AreaName": "Continent", "RegName": "Region"},
    inplace=True,
)

# let's examine the types of the column labels
all(isinstance(column, str) for column in df_Canada.columns)

# it returns False, we need to convert them to strings
df_Canada.columns = list(map(str, df_Canada.columns))

# set the country name as index - useful for quickly looking up countries using .loc method
df_Canada.set_index("Country", inplace=True)

# add total column
df_Canada["Total"] = df_Canada.select_dtypes(include="number").sum(axis=1)

# let's view the first five elements and see how the dataframe was changed
print(df_Canada.head())

# Pie chart, where the slices will be ordered and plotted counter-clockwise:
# Let's use a pie chart to explore the proportion (percentage) of new immigrants
# grouped by continents for the entire time period from 1980 to 2013.

# Group countries by continents and sum the numeric columns
df_continents = df_Canada.groupby("Continent").sum()

# The groupby method returns a groupby object before applying aggregation
print(type(df_Canada.groupby("Continent")))

# Display the first few rows of the grouped DataFrame
print(df_continents.head())

# autopct create %, start angle represent starting point
df_continents["Total"].plot(
    kind="pie",
    figsize=(7, 6),
    autopct="%1.1f%%",
    startangle=90,
    shadow=False,
    textprops={"fontsize": 8},
)  # Reduce font size

plt.title("Immigration to Canada by Continent [1980 - 2013]")
plt.axis("equal")
plt.show()

# Let's improve the above pie chart by adding custom colors, exploding some continents
colors_list = [
    "gold",
    "yellowgreen",
    "lightcoral",
    "lightskyblue",
    "lightgreen",
    "pink",
]
explode_list = [
    0.1,
    0,
    0,
    0,
    0.1,
    0.1,
]  # ratio for each continent with which to offset each wedge.

df_continents["Total"].plot(
    kind="pie",
    figsize=(10, 8),
    autopct="%1.1f%%",
    startangle=90,
    shadow=False,
    labels=None,  # turn off labels on pie chart
    pctdistance=1.12,  # the ratio between the center of each pie slice and the start of the text generated by autopct
    textprops={"fontsize": 8},  # font size of percent labels
    colors=colors_list,  # add custom colors
    explode=explode_list,  # 'explode' lowest 3 continents
)

# scale the title up by 12% to match pctdistance
plt.title("Immigration to Canada by Continent [1980 - 2013]", y=1.05)

plt.axis("equal")

# add legend
plt.legend(labels=df_continents.index, bbox_to_anchor=(1.1, -0.1), loc="lower right")

plt.show()
# Using a pie chart, explore the proportion (percentage) of new immigrants grouped by continents in the year 2013.
explode_list = [0.0, 0, 0, 0.1, 0.1, 0.2] # ratio for each continent with which to offset each wedge.

df_continents['2013'].plot(kind='pie',
                                figsize=(10, 8),
                                autopct='%1.1f%%', 
                                startangle=90,    
                                shadow=False,       
                                labels=None,                 # turn off labels on pie chart
                                pctdistance=1.12,            # the ratio between the pie center and start of text label
                                textprops={"fontsize": 8},
                                explode=explode_list         # 'explode' lowest 3 continents

                                )

# scale the title up by 12% to match pctdistance
plt.title('Immigration to Canada by Continent in 2013', y=1.05) 
plt.axis('equal') 

# add legend
plt.legend(labels=df_continents.index, bbox_to_anchor=(1.1, -0.1), loc="lower right")

# show plot
plt.show()